# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAINED_DATA: train.tsv 
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_DATA_TRAIN: train.pkl
  FEATURIZED_DATA_TEST: test.pkl
  TRAINED_MODEL_DIR: model
  MODEL_DIR: model
  MODEL_NAME: model.pkl


metrics : 
    SCORES: scores.json


plots:
    PRC: prc.json
    ROC: roc.json

source_data:
  data_dir : json
  data_file: data.xml

  